name: cmd
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        cd components/cmd && make test
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./components/cmd/c.out
        flags: cmd-codecov
        name: cmd-codecov
        fail_ci_if_error: true
        
    - name: Build
      run: cd components/cmd && make build

    - name: Cross Platform Build
      uses: crazy-max/ghaction-xgo@v1
      with:
        xgo_version: latest
        go_version: latest
        dest: dist
        pkg: ./components/cmd/entry
        prefix: aid
        targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
        v: true
        x: false
        ldflags: -s -w

